### PR TITLE
Replace "Now Playing" with "Currently recording" on fullscreen osd

### PR DESCRIPTION
**Pull request by nemphys**
Replace "Now Playing" label on fullscreen osd with "Now Recording" (+icon) when recording.

### CODE REVIEW

**Comment by opdenkamp** [comment]
I'll wait for Jezz_X's approval for skin changes.

**Comment by JezzX** [comment]
What I don't like about this (and discovered this with the other commit) is that it assumes that people only have 1 tuner and are watching what is currently recording, because all i does is show it in the currently playing info.   What it really needs to do is check to see if the currently recording title "PVR.NowRecordingTitle" matches the currently playing title in this case before showing it.

Since a lot of the time it probably wont match the best idea is to keep "Now Playing" they and add in a right aligned label (and the icon) on the same line that says "Recording [_]" if its the same channel you are watching and "Recording (channel Name) [_]"  if it does not   [*] is the icon btw

I also don't like the idea of adding the icon after the label I'd rather have a slow flashing one on the right hand side

**Comment by nemphys** [comment]
You are not right about this one. Actually, I have 2 tuners and it works as expected; if you check the implementation of the function Player.IsRecording, you will notice that it turns true if the channel that actually plays is being recorded.
As for the icon placement, etc, this is objective. If you decide that you don't like it, I'll pass and keep it just for my builds.

**Comment by JezzX** [comment]
Sorry you are right for some reason my brain was thinking you used PVR.IsRecording like is used on the home page not Player.Recording.  
Now I guess the question is which one do we think would be best, to show your recording the current channel or recording anything at all ? opdenkamp any thoughts on that one ?

**Comment by opdenkamp** [comment]
I didn't test this change myself. will have a look at it this evening.

**Comment by nemphys** [comment]
Obviously, my opinion is that, when viewing in fullscreen, since the user's only interaction at the moment is with the specific channel, the user would want to know if this specific channel is recording. Outside the fullscreen video mode (eg. channels list or home screen), the user currently (after the latest commits) knows exactly what is recording and for which channels.

**Comment by JezzX** [comment]
Ok I've come to the conclusion I'm happy with this but not happy with the way you have implemented  it.
It doesn't need to be a grouplist control because the rec image is on the left all you need to do is move over the "Recording" label and shorten it a little.  Maybe put them in a normal group for the visible condition?

If you make those changes and update the pull request I'm happy to have it merged

**Comment by nemphys** [comment]
ok, will do tonight

**Comment by nemphys** [comment]
OK, updated the commit, please review and pull if all is ok

**Pull request merged**
