### PR TITLE
database ResultQuery: only return true if num_rows greater 0

### PR DESCRIPTION
**Pull request by FernetMenta**
I noticed that because default video settings were always incorrect.

### CODE REVIEW

**Comment by opdenkamp** [comment]
without looking into the code, the method that calls ResultQuery is probably behaving incorrectly in that case, so change it there.

the return value for ResultQuery() is "True if the query was executed successfully, false otherwise."

**Comment by FernetMenta** [comment]
the method which calls ResultsQuery in this case is CPVRDatabase::GetChannelSettings. it looks ok. ResultsQuery returned true in fact of the entire table was empty.

**Comment by opdenkamp** [comment]
that behaviour is correct because the select query was executed successfully. an empty result is perfectly valid.

I'll have a look at GetChannelSettings(). it's probably expecting that it returns a result (with at least one row in it) if the return value of ResultQuery() is true.

**Comment by FernetMenta** [comment]
ok, thanks!

**Comment by opdenkamp** [comment]
fixed in 9527edd12105091b8d3ad74e68d87472cbcb7d39

btw, in your patch, "if (true) bReturn = true" should have been "bReturn = condition" anyway ;-)

**Comment by FernetMenta** [comment]
yeah, this was a bad one :) but you fixed it already and that's good!

**Pull request closed without merging**
