### PR TITLE
pvr: fix pvr epg search functionality and intial values

### PR DESCRIPTION
**Pull request by nemphys**

### CODE REVIEW

**Comment by opdenkamp** [comment]
I am already refactoring this code locally. I'll have a look at your changes. Might incorporate some of them if I didn't change it already.

**Comment by nemphys** [comment]
Shit, took me a long time to see through this mess

**Comment by opdenkamp** [comment]
sorry, didn't know you were working on this too. your work wasn't all in vain, as I was just working on reading the time from the input properly. used your sscanf line for that :)

but you are right, it's a complete mess, so I decided to clean it up.

**Comment by nemphys** [comment]
Btw, I initially tried to use the SetAsTime function of CDateTime (instead of using 1960,1,1), which actually sets a date of 1600/1/1 or something. The weird thing is that if the given time was 0:00, using this method produced a time of 23:59 (!)
Smells like a bug and that's why I used SetDateTime.
Furthermore, since you're working on the search function, I noticed that after the first search, if the users doesn't manually clear the results (for which, btw, there is a very informative "Unassign content" context menu option, which should definitely be changed to "Clear search results") the search runs every time the user scrolls over the respective sidebar item. Maybe the results should be cleared automatically once the user leaves the search menu.

**Comment by opdenkamp** [comment]
yeah it's set to 1601.0.0 for some reason. was wondering why too, because it'll result in a negative system time / overflow. appears to be a bug indeed.

nearly cleaned out all the mess now. and while fixing this, I noticed that half of the options in the dialog don't work properly :)

**Comment by opdenkamp** [comment]
right, 1-1-1601 is epoch on windows and windows uses a lower resolution for this.
so it'll probably work fine on windows and fail on other os'es.

**Pull request closed without merging**
