### PR TITLE
new demuxer https://www.vividas.com added to ffmpeg lib

### PR DESCRIPTION
**Pull request by bigtarget**
That demuxer is needed for http://www.iplex.pl/ service to watch it by polish plugin from polish plugin repository
http://sd-xbmc.googlecode.com/files/repository.sd-addons.eu.zip.

It works i tested it.

Thank you in advanced for adding it.

### CODE REVIEW

**Comment by bigtarget** [comment]
There is main thread for that plugin:

http://translate.google.pl/translate?sl=pl&tl=en&js=n&prev=_t&hl=pl&ie=UTF-8&layout=2&eotf=1&u=http%3A%2F%2Fhdtvpolska.com%2Ftopic%2F26007-plugin-pod-xbmc-polska-tv-weebtv-i-filmyseriale-ekinotv%2F

**Comment by opdenkamp** [comment]
thanks. I'll have a look at it, but I'll have to warn you that it will not be included in Eden-pvr, but only in the master branch. it's too late to add new features to Eden-pvr.

**Comment by bigtarget** [comment]
it is not new feature, but just new format which is separated to others. It doesn't infect other formats, just new stream demuxer vividas.

**Comment by opdenkamp** [comment]
please send this pull request to mainline xbmc: https://github.com/xbmc/xbmc
it'll be merged automatically after a few days after being accepted there.

**Pull request closed without merging**
