### PR TITLE
RFC: Incremental EPG updates

### PR DESCRIPTION
**Pull request by manio**
As you requested - I am opening pull request for the changes discussed in issue #316. Please comment.

### CODE REVIEW

**Comment by manio** [comment]
Lars, as you can see I've added new argument to GetEPGForChannel function. Do you think it would be a better idea to add additional API function, called eg GetEPGSince and also add a new addon capability (eg: bSupportsIncrementalEPGUpdates)?

**Comment by opdenkamp** [comment]
I'll review it in more detail as soon as I got time. thanks.

**Comment by opdenkamp** [comment]
I'll incorporate these changes in the external-addons branch, since I'm already working on some interface changes in there.

**Comment by manio** [comment]
btw: I think that similar timestamping would also be great when doing channel updates. I did not mention about it yet, but if you're making an api changes - it would be great to have similar thing in channel updates (update only changed channels since last update in one bulk process and not asking if every single one has changed).

**Comment by schumi2004** [comment]
@adamsutton is your tvheadend repository the latest up-to-date version of tvheadend? It's for testing purpose.

**Comment by adamsutton** [comment]
It depends what you mean by up to date ;)

My epg-rewrite branch contains my rewrite of the TVH EPG code. But it's still in flux as I'm adding new features. Although things are beginning to stabilise.

However I've not yet included any of the stuff related to this particular feature, simply because I've been busy getting other bits to work and I think we need to agree on what is required in the API etc.. That being said because of the way I've organised the code it should be a relatively trivial feature to add (famous last words).

If you want to have a chat about this, I'm on IRC (adamsutton). And I'm usually lurking around in #hts and/or #xbmc-pvr.

Adam

**Comment by opdenkamp** [comment]
Now that PVR support has been merged into mainline XBMC, every pull request must be sent as a pull request to mainline XBMC too: https://github.com/xbmc/xbmc/pulls

That's why I am closing this one. Sorry for the trouble.

**Pull request closed without merging**
