### PR TITLE
pvr: added selection of channel groups within channel osd

### PR DESCRIPTION
**Pull request by xhaggi**
I added the possibilty to change the channel groups within the channel osd to improve handling of channel groups while watching live tv.

Now you can use left/right key to change the channel group without stopping the current playback.

### CODE REVIEW

**Comment by opdenkamp** [comment]
looking good.
please fix the indenting in the patch, and stick the log message in g_PVRManager.SetPlayingGroup() instead. thanks.

**Comment by xhaggi** [comment]
i fixed the identing .. it was the default template formatter ;) .. and removed the logging.

it is possible to merge this in the eden-pvr branch too?

**Comment by xhaggi** [comment]
something wrong with the last changes??

**Comment by opdenkamp** [comment]
yes, could you squash this up please, and remove the translation + revert commit. thanks

**Comment by xhaggi** [comment]
okay it's done ;)

**Comment by opdenkamp** [comment]
will be merged in in a moment, and backported to Eden-pvr. thanks

**Pull request closed without merging**
