### PR TITLE
pvr: renable subtitles

### PR DESCRIPTION
**Pull request by pipelka**
this is analog to the teletext fix and re-enables dvb subtitles.

### CODE REVIEW

**Comment by nemphys** [comment]
This does not seem to work right; I tried watching a channel with both italian and english subs and it was trying to render both of them at the same time (the language setting had no effect and would revert to the first right after setting it).
Without this patch, the subtitle language is set correctly, but subtitles are actually rendered on screen in a random manner (ie. most of the subtitles don't display at all, some display correctly).
Any ideas?

**Comment by opdenkamp** [comment]
you'll need to check for which stream you should actually return true in IsBetterStream().
for teletext, this is correct, since there's only one teletext stream, but for subtitles, you need to check which one you actually want to enable.

**Comment by opdenkamp** [comment]
this should do the trick

**Comment by pipelka** [comment]
great. thanks.

**Comment by nemphys** [comment]
Don't know if it is the specific streams from SKY Italy, but although the first subtitle language (italian in this case) is displayed properly, nothing is displayed when the second language (english) is chosen.
Reopen, or a new issue?

**Comment by opdenkamp** [comment]
I've tested streams with multiple languages here, and it works properly.
are those channels working correctly in another player?

**Pull request closed without merging**
