### PR TITLE
pvr: added missing translations

### PR DESCRIPTION
**Pull request by xhaggi**
fix previous pull request, now only pvr related translations

### CODE REVIEW

**Comment by xhaggi** [comment]
i removed the last unnecessary merge commit

**Comment by opdenkamp** [comment]
i can see a number of different translations for "hide" in the german translation file: verstecken, ausblenden, verbergen, nicht anzeigen. wouldn't it be a better idea to use the same one where possible? disclaimer: i'm not german, so if this doesn't apply, let me know and i'll merge it in like this.

**Comment by xhaggi** [comment]
that's the german pronunciation .. we have 3 words for one in english, so in some cases you use "verstecken" in other "nicht anzeigen" etc. ... so it's okay

**Comment by opdenkamp** [comment]
cool, thanks, merged.

**Pull request merged**
