### PR TITLE
Add propper Live TV support to the Player JSON API

### PR DESCRIPTION
**Pull request by RobertMe**
Does what the title says :)

With this in you can remove PVR.ChannelUp and PVR.ChannelDown as the same can now be done with Player.GoNext (/GoPrevious). GoTo uses the "position" param as channel number (within the current group). I've added a "islive" property to the player. GetItem now returns (some) details about the channel (probably will be expanded later on).

I've also added a PVR.OnCurrentEpgItemChanged notification. This can't be used yet as there is no way to request data back (work in progress). But we've already discussed that epgid + starttime should be the events identifier so that doesn't change.

Another thing I'm unsure off is changing the AnnouncementFlag (IAnnouncer.h) to being two bytes big. But I think you also don't know if there are any consequences to it.

### CODE REVIEW

**Comment by opdenkamp** [comment]
general: i don't know json-rpc very well, but i don't think you really need that new enum value, when radio is just audio and livetv just video. the only thing it adds is some metadata, that you can probably just add to video/audio descriptors, and leave empty when you're not playing a pvr channel, right?

@montellese could you have a look at this one please. it will be added to the json-rpc pr for mainline when done.

**Comment by Montellese** [comment]
Is the implementation in this PR meant to replace the PR with PVR specific JSON-RPC methods that already exist in the XBMC repo or are these just additional fixes?

I agree on the additional enum values. Isn't it possible to treat radio as audio and do some additional check in a specific implementation to see if it's PVR are not (same for livetv being video)?

**Comment by opdenkamp** [comment]
@Montellese yeah it's a PR to go on top of https://github.com/xbmc/xbmc/pull/1412
the PR that i created was just the code that wasn't merged in when PVR was merged. @RobertMe was already working on the pvr bits for json-rpc when we merged. so this will be added to PR 1412 when ready & ok

**Comment by RobertMe** [comment]
Okay, will see if I can remove LiveTV enum. I thought it might be easier to just add the enum value and adding the cases instead of having to write an if for it all the time. But in the end I think the exception to the "rule" is more common then the "rule" itself. (the rule being: audio/video is different than LiveTV)

**Comment by opdenkamp** [comment]
@RobertMe last merge window before feature freezing for Frodo opening in 4 days. any chance you can get this updated after the comments? otherwise it won't be included in Frodo.

**Comment by efremov476** [comment]
:/ Will be very appreciate if we can integrate type Live TV in GetPlayer methods....

**Comment by opdenkamp** [comment]
closing since it's being picked up by @Montellese now

**Pull request closed without merging**
