### PR TITLE
build + bugfix VNSI pvrclient addon under win32 with VC 2010

### PR DESCRIPTION
**Pull request by lucianm**
Here we go, Lars, I've got it right eventually. Note my 3 commits (they are based upon each other chronologically). Surely all PVR clients could use some refactoring, but right now I tried to just make VNSI work and align the code to the existing ones, a bit. Cheers, Lucian

### CODE REVIEW

**Comment by pipelka** [comment]
Lucian,

As i told you this adds a lot of stuff that isn't needed.

**Comment by lucianm** [comment]
Hi Alex,

as I stated before, I just wanted to make it work _now_ for fellow VDR users from http://www.vdr-portal.de, for a friend of mine, for myself... and am not claiming that this is the ultimate solution to go for.
As of the stuff that isn't needed, please elaborate. I have to confess that I did not modify the sources with proper knowledge of the whole architecture of XBMC, or proper patterns of multi-platform development. But I could notice that the code of all PVR clients could use some better design with respect to the common tasks, like connecting to their backends and the way threads, endianess and some data types are treated with respect to multi-platform development. So even if I cannot exactly answer your questioning about why I included StdString.h for example, my answer is simply: I tried without and had bad failures with connecting to the server part, with interpretation of streamed data, I suppose due to the way several system headers are included with or without that whole "stuff".
So I tried to align the code to that of the tvheadend, MediaPortal and the obsoleted vdr-streamdev, I find it pitiful that these addons o not share as much as possible and opnly differ in their specialities.
You went the mingw32 compiler route, well, while I eventually managed to build VNSI that way, I never managed to get it working, and found that a proper VC 2010 project just as the other addons have (left aside mythtv for which, as most of us, I don't care as I don't use it, just like Lars uses just tvheadend and linux and so on) would be rather benefical, would even ease the way for developers more familiar with Visual Studio and windows than other IDEs or platforms, to try and contribute. And once I managed to get it started and even connecting to VDR, there still was the big endianess problem which prevented stream timing information to reach the player in non-altered form, please see the the iomplementation of ntohll and htonll added by my patch, I'm really wondering how VNSI built with mingw would properly handle that, but I might be wrong and it would be handled by the implementation in mingw libraries.
So I'm more than open for improvements of the situation and am by no means trying to diminish your work done on VNSI, I just want us to find a good solution and also talk about improvements and features. Btw, do you, alex happen to stop by either in the XBMC forums, or the german VDR Portal or the general VDR mailing list, or even more interactively on freenode #xbmc-pvr?

**Comment by pipelka** [comment]
Lucian,

You opened a pull request and i commented. I don't think this will be pulled in the current state (i may be wrong because it's not my repo). If you want it to get pulled, make it proper.

I do not waste my time on forums or IRC chats.

Alex

PS: Yes. I want it to build with VS2010. But please do not add unused code. Just create a project file and add bug-fixes.

**Comment by lucianm** [comment]
Alex,

I also do not expect that Lars would pull the code in its current state, I can agree there is partly unused code, but this is  mainly due to the fact that I just copied files from the other addons and did not reduce their code to the bare minimum yet. The reason for this was that all of them need a refactoring, badly, and as much as you're not a friend of unused code (which I agree with), I am an even worse friend of redundant code, and my opinion is that there has to be a re-design. My problem is I just cannot have such an overview as you or Lars can have and wanted to trigger a discussion on what has to be done for this, and do it _really_ properly, to avoid too much work which would be obsoleted again, as I could not find any design documents of how PVR is to be implemented. We have to start somewhere, and on the other hand I wanted to attract also VC devs into this, possibly there are more of them. So there still need to be defined what that proper way is, and this should not be the case just for one single PVR addon.

Lucian

**Comment by opdenkamp** [comment]
Lucian, Alex,

I've read through the patch quickly and read your comments.

First of all, the add-ons need some serious clean ups, I agree. I haven't done much work on the tvheadend one myself, except for keeping it working, but I know there's a lot of dupe code between add-ons that shouldn't be there.

There are also some other issues with this pull request, some of which Alex already pointed out. Consider these things before sending a pull request:
- only send clean patches. no half completed work.
- don't send pull requests with merge commits in them. rebase your patches instead. and squash the "fix typo" commits into the change you actually want to send me.

**Comment by opdenkamp** [comment]
Hi Lucian,

another thing I forgot to add to my comment yesterday: rename your libOsDependent to libTcpSocket or something and don't try to stick all os dependent stuff in 1 lib. Also, have a look at what code already in xbmc's tree. All the pvr clients got some utility methods for sockets, threading and strings. Similar code is present in xbmc too.

So, if you're going to clean this dupe code up (which is a good thing), use separate libs and reuse existing code where it makes sense.

**Comment by pipelka** [comment]
Lars,

How should this work if the PVR addons get separated from XBMC.

Alex

**Comment by opdenkamp** [comment]
Hi Alex,

You can still link against that new lib (or more libs), as long as that lib itself doesn't have dependencies on xbmc specific code. I'm already doing the same with libhts, which had a copy both in xbmc/lib and xbmc/pvrclients/tvheadend before.

Separating the pvr clients from the tree doesn't mean it can't link against the libs we already got in there, which can be considered third party components that have no connection with xbmc. It just means that we'll be able to build and distribute clients separately, without having to build and distribute the whole of xbmc every time. Or to explain it in "user speak", they just copy over one or more dll/so and they upgraded the client.

Just don't create any dependencies in libs, link them statically into the client, and it should be fine.

If you see a better solution to remove the redundancy in the pvr clients or think this will get us into trouble, feel free to propose it and if it's a better solution, we'll go that way. But the redundant code has to go, I'm sure you'll agree with that.

Lars

**Comment by pipelka** [comment]
Hi Lars,

I'm familiar with the plugin concept.

Currently I see 3 ways to prevent code duplication:
- using shared libraries in the addon code. 
  bad: different users may have different versions installed, libs may be missing
- static linking of code.
  bad: increases binary size
- provide common used functions via the PVR API

Alex

**Comment by elupus** [comment]
I see increased binary size as a very little problem. It increases load time slightly and adds some ram needs, but it will be small compared to the full xbmc anyway. And we'll mostly only run one pvr client at a time.

Extending the PVR API means always having to maintain compatibility for that API. That is a major burdon.

**Comment by opdenkamp** [comment]
Indeed. We can create self-containing pvr clients in an easy and elegant way by linking these (small) libs statically.

ps Alex: you were asking about the API changes earlier. they're all documented on the forums. I know you told you don't want to waste time on the forums or irc, but at least have a look at the pvr development section of the forums once in a while. vnsi users are reporting problems there, which should interest you if you're maintaining that code. and I announced the API changes before they were merged into the main tree and documented later changes here: http://forum.xbmc.org/showthread.php?t=97764

Lars

**Comment by pipelka** [comment]
Lars,

I'm not aware of any questions about the API changes. Anway,... 
I think my inbox tells me enough about bugreports, user problems and so on.

Now on the topic:

If the general agreement is a static library i can perfectly live with that.

Maybe there shouldn't be a big one trying to cover all topics.
Smaler parts covering threading, network communication, and so on would be prefered by myself.

Alex

**Comment by opdenkamp** [comment]
Alex,

that's what I suggested before and what I just discussed on irc with Lucian. 1 lib for threading, 1 for tcp.

and about that api change stuff: that was FernetMenta, not you, sorry :) I still would suggest you visit the forums occasionally :)

Lars

**Comment by pipelka** [comment]
Lars,

I'm an old fart. irc is for young dudes. ;-)
Sometimes I'm in a bad mood and people around me just have to notice that (i force them to do). ;-)
But usually I'm quite handsome (especially if the TV box works and my wife has no reason to blame it on me).

Regards,
Alex

PS: Yes. My wife is the reason why I'm involved in all of this. ,-)

**Pull request merged**
