### PR TITLE
vnsi addon: support for channel groups

### PR DESCRIPTION
**Pull request by pipelka**
load channel group definition from the server.

### CODE REVIEW

**Comment by opdenkamp** [comment]
the configuration setting to sync channel groups isn't needed. there's already an option to control this in the general pvrmanager settings.

**Comment by pipelka** [comment]
Wow, I didn't know that XBMC is able to "create channel groups automatically".
Don't get me wrong, but sometimes I know what I'm doing ;-)

This switch does what it says: It creates the channel groups automatically on the server (by grouping the channels by provider)

**Comment by opdenkamp** [comment]
maybe you do, but our users don't and might confuse it with "sync channel groups with backends" (as I did), which creates channel groups automatically, but on xbmc's side.

so add "on the server" to the description of the config parameter.

**Comment by pipelka** [comment]
As you command, my master.

**Comment by opdenkamp** [comment]
I'll add "pretty please" next time.

**Comment by pipelka** [comment]
Good boy ;-)
Ok. That's enough for today. ;-)

**Pull request merged**
