### PR TITLE
Add channel filter

### PR DESCRIPTION
**Pull request by manio**
Hi Lars,
This patch is adding feature which I've missed a lot: channel filtering by name :)

First I've considered to put it at the end of all entries but when did
it that way, there was a problem with filtering Radio channels.
Finally I've put the filter entry between TV and Radio because it is
now possible to filter both of them.

Screenshot: http://skyboo.net/xbmc/screenshot224.png
And after filtering: http://skyboo.net/xbmc/screenshot225.png

### CODE REVIEW

**Comment by nilzen** [comment]
I'm either blind or this PR only contains a change to the skin file and no code changes?

**Comment by manio** [comment]
Indeed. This is handled by xbmc CGUIMediaWindow code (same code is used when you filter eg your audio files).

**Comment by opdenkamp** [comment]
please don't add it there, but as context menu item or some other way. now it's showing up the same as one of the menu items for the tabs (tv, radio, etc.).

also, the same would have to be added for radio channels.

**Comment by manio** [comment]
Ok, sure. I'll add it in context menu.

**Comment by manio** [comment]
Fixed. Please review...

**Comment by opdenkamp** [comment]
thanks, merged

**Pull request merged**
