### PR TITLE
smaller code cleanup

### PR DESCRIPTION
**Pull request by pipelka**
removed unused code and added the missing configuration file.

on the pull request:
it's strange that the diff is right but the list of commits also contains the already applied first patch.

### CODE REVIEW

**Comment by opdenkamp** [comment]
did you do a "git pull --rebase" after I pulled your earlier changes?

**Comment by pipelka** [comment]
no. i must confess i'm quite new to git.
should this fix the issue if i do it now ?

**Comment by opdenkamp** [comment]
you also have "merge commits" in this pull request. only the things you want me to pull should be in the pull request.

I'll cherry-pick the relevant commits after reviewing them.

have a look at the git(hub) manual next time you send a pull request :) thanks

**Comment by pipelka** [comment]
wow. i think this will take some time to fix the mess.
old dogs and new tricks, ...

**Comment by opdenkamp** [comment]
lol, now you completely messed things up :)

I reviewed the commits quickly. One question: you removed the netlog methods, but you're still doing m_req->extract_U8(); without doing anything with the returned value. does that mean that it's still part of the protocol and that you're just reading the value to increase the read pointer?

cherry-picked:
- 2d3a81fd5b7e111b5a0dd5ffee0b339bb9e65166
- dd608be9cf03c04c3764c03ed139557105e0a33d
- 7b666417210d6152b567397a072f71fb562df70d
- b97a17afa17f345cb990e610350596e24270cb7a

**Comment by pipelka** [comment]
right. i didn't want to break the network protocol.
as a first git success i restored the original (smaller) mess ;-)

**Pull request closed without merging**
