### PR TITLE
vdr-vnsi server / client cleanups

### PR DESCRIPTION
**Pull request by pipelka**
client:
- removed recordingdir / usedirectory options
- removed useless code

server:
- small packet handling changes

### CODE REVIEW

**Comment by opdenkamp** [comment]
I'm not sure if the queue code should be removed. Correct me if I'm wrong, but isn't the processing of packets blocking the input of new packets?

**Comment by pipelka** [comment]
The member m_queue is only used in the ReadResult function. It waits for the right packet and then discards the queue (via swap). I think this should handle out of order packages, but this will never happen. If it happens there is something wrong with the server.

**Comment by pipelka** [comment]
Hmm,...

Just to explain how useless the original code is:

there is one push() operation to m_queue.
there aren't any pop() or front() operations.
m_queue isn't referenced from any subclasses or from outside.

So what is a queue for if it's only filled and then deleted ?

**Comment by opdenkamp** [comment]
ok pulled. thanks.

**Pull request closed without merging**
