### PR TITLE
[PR] deadlock in json-rpc PVR.ChannelSwitch

### PR DESCRIPTION
**Pull request by FSSDawid**
see title

(ticket edited by opdenkamp)

### CODE REVIEW

**Comment by FSSDawid** [comment]
private to public

**Comment by FSSDawid** [comment]
now it looks ok but while switching i get:
http://pastebin.com/LAxfPLFg
I think a lock or something more in needed ?

**Comment by opdenkamp** [comment]
fixed in d48d118279dfb3215357a41878e8207d09498919
the error message is probably just the demux thread that closes the connection. does the switch work?

**Comment by FSSDawid** [comment]
nop :( I got a error in Tvhedend ... LOG: http://pastebin.com/LAxfPLFg 
XBMC crashes

**Comment by opdenkamp** [comment]
pastebin the crashlog or gdb backtrace please

**Comment by FSSDawid** [comment]
Can't get it to crash now... it just hangs... I'm building for openelec.

**Comment by FSSDawid** [comment]
@opdenkamp just telnet to port 9090 and paste:

{"method":"PVR.ChannelSwitch","id":1,"jsonrpc":"2.0","params":{"channelid":1}}

and after a while

{"method":"PVR.ChannelSwitch","id":1,"jsonrpc":"2.0","params":{"channelid":2}}

**Comment by FSSDawid** [comment]
Finally got it to work  :D 

```
CDVDPlayer *player = (CDVDPlayer *) g_application.m_pPlayer;
player->SwitchChannel(*channel); 
```

I will post a PR today after I compile it with openelec and second ubuntu but it looks promising  :) 
spent 5h to get this going keep your finders crossed :D

**Comment by elupus** [comment]
FSSDawid.. It's much better to use OnAction functionality.. There is an action for channel changes i think.

**Comment by FSSDawid** [comment]
@elupus what do you mean by "onAction" ? I'm just trying to improve the channel switching so on every switch it doesn't hit to menu. 

g_PVRManager.PerformChannelSwitch(*channel,false) 

Just don't seem to do very well it's just like the player is not switching the stream but PVRManager is... And the GUI stops responding, but the PVRManager and other threads are doing fine. 

Sorry for my stupid questions but I'm just discovering the XBMC code logic.

Regards!

**Comment by elupus** [comment]
dvdplayer has a OnAction function that handles results of keypresses. Same logic should be used for external actions on the player. Calling functions not in IPlayer interface is not a good idea.

**Comment by FSSDawid** [comment]
@opdenkamp is there any other way that I can try to make this work ? This works flawless and even displays the preview.
take a look at https://github.com/FSSDawid/xbmc/commit/1799a68ad219188f869d6b064666aa2d00b7858f I won't make a PR  as @elupus doesn't like it ;) 

@elupus I have looked at the onAction stuff but I don't think this is the best solution for this.

**Comment by opdenkamp** [comment]
I'll have a look at it when I got time. I'll change the title of this report and reopen it, so I won't forget.

**Comment by elupus** [comment]
@FSSDawid, reason i don't like it is that it will crash and burn badly if the player is not dvdplayer...

**Comment by elupus** [comment]
You can create a CAction with the id: ACTION_CHANNEL_SWITCH with an amount with the channel number you want to switch to and then you send that using g_applicationMessenger.SendAction().

**Comment by FSSDawid** [comment]
@elupus that's a hell of a good reason :)

> You can create a CAction with the id: ACTION_CHANNEL_SWITCH with an amount with the channel number you want to >switch to and then you send that using g_applicationMessenger.SendAction().

Yes I could if I know how much that is im switching by channel ID so it's independent from groups... Thats why wi can't just use PVRManager.ChannelSwitch which is group based...
Well I think I'm going to drop the Player idea and find try to find the dedlock instead. 
What I have noticed:
If I try to performChannelSwitch from a remote TVHeadend it works... The problem is in the local network something is just going to fast ;) also performChannelSwitch with preview set to TRUE works as expected... but preview just changes the channel description (doesn't switch the tv stream). 

Well back to the drawing board ;)

**Comment by FSSDawid** [comment]
@elupus just found out that 
IPlayer class implements SwitchChannel

```
IPlayer *player = (IPlayer *) g_application.m_pPlayer;
return player->SwitchChannel(*channel) ? ACK : InternalError;
```

Is this ok to use ?

**Comment by elupus** [comment]
Ok, then it won't crash directly. But it's called from a thread which
doesn't control create,destroy of the player object, thus not safe.

Should be sent through appmessage system anyway.

**Comment by FSSDawid** [comment]
@elupus so assume this would be the right way to do it ? 

  m_messenger.Put(new CDVDMsgType<CPVRChannel>(CDVDMsg::PLAYER_CHANNEL_SELECT, channel));

**Comment by elupus** [comment]
That may be part of it. But the point is that the call should be done through CApplicationMessenger. (g_applicationMessenger). That makes sure you make the call through app thread which is the only thread that can guarantee the player object is valid when the call is made.

**Comment by opdenkamp** [comment]
this should do it (in 3 commits thanks to my sloppiness)

**Comment by FSSDawid** [comment]
Thanks tested and it's working grate :)

**Pull request closed without merging**
