### PR TITLE
skin/confluence: add channel icon and channel name on pvr timers view.

### PR DESCRIPTION
**Pull request by nemphys**
Looks much cooler in my opinion and I think this information is quite important for the timers view.

### CODE REVIEW

**Comment by JezzX** [comment]
got a screenshot ?

**Comment by nemphys** [comment]
Will upload one later tonight

**Comment by nemphys** [comment]
Here you go:
http://www.imageupload.org/?d=4DC96F5F1

**Comment by nemphys** [comment]
Any comments?

**Comment by nemphys** [comment]
Just updated the commit because of a conflict with one of today's commits

**Pull request merged**
