### PR TITLE
Live TV section: Czech translation added

### PR DESCRIPTION
**Pull request by babca**
I've added czech #19xxx language strings and updated confluence skin strings.xml

### CODE REVIEW

**Comment by opdenkamp** [comment]
thanks, but the non-pvr labels (the ones that are in the standard XBMC branch) should be sent there, or it'll take months before they get merged back into that branch, and will lead to merge conflicts if someone decides to fix in there too.

**Comment by babca** [comment]
ok, so I'm going to create a new pull request to xbmc/xbmc with updated non-#19xxx strings.

**Comment by opdenkamp** [comment]
thanks

**Comment by babca** [comment]
commit 9c41165: Oh, I don't remember that I've committed any code here today (that's an update for xbmc/xbmc master branch) – maybe it's my fault (?)
You can just ignore/remove this 9c41165 commit.. or merge it all, I'll add PVR strings again, that's no problem for me.

Or should I perform a new final commit right now? Sorry, I'm new here! :-)

Cheers

**Comment by opdenkamp** [comment]
please create 1 commit that wraps it all up, and push it to your PR branch. please create the PR from the master branch though, not the Eden-pvr branch

**Comment by babca** [comment]
I've just created a new pull request to master branch.

OT: Is this a known bug?
http://img837.imageshack.us/img837/3348/screenshot001qt.png
http://img715.imageshack.us/img715/461/screenshot003tc.png
http://img836.imageshack.us/img836/3154/screenshot004zp.png

**Comment by opdenkamp** [comment]
I have seen this when using xvba. totally forgot to ping @FernetMenta about that one :)

**Comment by FernetMenta** [comment]
I have seen the messed-up labels one or two times a couple of weeks ago but was not able to reproduce since then.

**Comment by opdenkamp** [comment]
@FernetMenta 
I can reproduce it sometimes when I start an h264 1080i stream first, stop it, and play an mpeg2 afterwards.
this also triggers another bug: when starting the mpeg2 stream, the screen flashes all the time, and the palette is wrong (colours inverted or something). this I can reproduce 100% of the times. let me know if you need samples.

now the labels get messed up after stopping the "flashing stream" about 1/10th of the times I try.
something not cleaned up or reinitialised properly perhaps?

**Comment by fritsch** [comment]
I remember this corruption at the time when xvba did not use xrandr correctly to refresh windows. As mpeg-2 is not handled through xvba, this could be a part of the issue? 

https://github.com/FernetMenta/xbmc/commit/1fa05ffc805ae2c958bf9103c87e5d0cf76e279d <- this commit fixed a lot of the corruption for users with Adjust Refreshrate to match video enabled. Perhaps a rare condition that it triggers?

**Comment by opdenkamp** [comment]
I get this on openelec, with that commit included.

**Comment by FernetMenta** [comment]
@opdenkamp 
some samples wold be great, will try to duplicate

**Comment by babca** [comment]
Shouldn't we start a proper ticket or topic for this somewhere?

Screenshots of starting a mpeg4 1080i stream first, stopping it, and playing an mpeg2 afterwards:
http://img849.imageshack.us/img849/6859/screenshot01hdstream.png
http://img141.imageshack.us/img141/8272/screenshot02sdstream.png
http://img263.imageshack.us/img263/2048/screenshot03fail1.png
http://img14.imageshack.us/img14/4705/screenshot03fail2.png
http://img338.imageshack.us/img338/3037/screenshot03fail3.png
http://img140.imageshack.us/img140/5663/screenshot03fail4greenb.png (blinking "inverted" and green)
http://img263.imageshack.us/img263/5663/screenshot03fail4greenb.png

Screenshots were captured on OpenELEC r9725 Fusion build. There is the same issue on r9963.
// I cannot reproduce labels corruption manually.

@fritsch 
I have 'Adjust Refreshrate to match video' disabled.

**Comment by FernetMenta** [comment]
should be fixed by:
https://github.com/FernetMenta/xbmc/commit/2f8921af82dcaf407e2d68954dba7f86e5a1d7c5

maybe this fixes other issues as well :)

**Comment by FernetMenta** [comment]
unfortunately the issue is not fixed by the patch i mentioned above. investigating .....

**Comment by fritsch** [comment]
I will retry to let amdxvba clean up its mess:
3.3.2 XVBADestroyContext from amd xvba-sdk:
Destroying context will release all sessions in this context and resources own by each session

I still know why the explicit cleaning was introduced, perhaps the cleaning by internal xvba routines are not that failsafe as expected. Will let you know the results.

**Comment by opdenkamp** [comment]
we should really be discussing this in a separate ticket instead of a translation PR :)

**Pull request closed without merging**
