### PR TITLE
pvr addons refactoring to reduce redundant code and build VNSI under VS2010 Express

### PR DESCRIPTION
**Pull request by lucianm**
Hi Lars,

please have a look at these, I tried my best so far, tried to follow as much as possible the things discussed and could successfully test VNSI on Linux and Windows. I hope that MediaPortal and TVHeadend also work well under Linux and Windows, but I don't have a setup to test that. I also uploaded a windows build here https://github.com/lucianm/xbmc/downloads especially for VDR users, should we already ask on the XBMC forums for testers, or do you want to wait for further code ammendments?

### CODE REVIEW

**Comment by opdenkamp** [comment]
I'll check out this code tonight. I wouldn't ask users to test this but rather wait until I include it, so it will be tested in a ppa release.

**Comment by margro** [comment]
I would like to test the Mediaportal changes first, because I don't want to have the os-dependent header removed completely and I've seen some changes that are probably not correct.

**Comment by lucianm** [comment]
On 19.04.2011 15:07, margro wrote:

> I would like to test the Mediaportal changes first, because I don't want to have the os-dependent header removed completely and I've seen some changes that are probably not correct.
> 
> Hi margro, so please test and report issues.

The thought about removing the os-dependent header was just to rather
use those headers in common, as discussed with Lars, Alex Pipelka and
eluplus. Note for example that Socket.cpp includes
"libTcpSocket/os-dependent_socket.h" and pvrclient-mediaportal.cpp and
timers.cpp include "libPlatform/os-dependent.h".

Now the current content of libTcpSocket and libPlatform may not be
optimally separated, or not accurate (libPlatform on linux is just
header files for example, on win32 it is also compiled and yet provides
those pre-built libs for pthreads...), but all this is what we should
discuss and sort out.

**Comment by opdenkamp** [comment]
@margro:
the os dependent stuff should go because there's a lot of redundant code in the pvr add-ons. every add-on has it's own implementation of threading and sockets and all of them are a bit different. that's why we'd like to have this code in /ilb and just let every add-on link what it needs (statically).

@lucianm
looking promising. added some comments to the commit. most of those comments apply to other parts of the code too.
some general comments:
*) I didn't look into the win32 implementations and scanned the posix ones quickly.

*) remove all the empty comments and at least add some documentation to the methods that are available on the interface.

*) please follow our coding guidelines and watch your identing.

*) remove the "utility" #define statements that aren't needed. or don't stick them in a header.

*) don't assert() to check your input on methods that are available on the public interface (indirectly).

*) check your input, at least on the public methods.

**Comment by margro** [comment]
@lucianm: I've added a few comment to your code. I've tested the MediaPortal addon (with close_() changed back to close() and I can confirm that everything still works fine.

@opdenkamp: I understand the ideas behind the code move to lib/ to be able to re-use the os-dependent stuff and I've seen the previous discussion. I agree with this change and it is a good first step to provide future PVR addon developers with more (shared) building blocks (these libraries and lateron threading etc.) that they can use to implement their addons.

A quick clarification on my previous comment about the removal of the os-dependent.h in the MediaPortal addon:
although it can be removed right now, I will need it again for the current version of the addon that I'm developing in my local branch for other os-dependent stuff which currently MediaPortal specific.
Therefore I would like to keep the os-dependent.h in the MediaPortal addon and include the libPlatform version from there and extend the local header (inside the pvr addon dir) with addon specific defines/code.

**Comment by lucianm** [comment]
Hi Lars & margro,

so I tried to follow all of your suggestions and committed the fixes separated such that they could be sqashed in the original commits...

**Comment by opdenkamp** [comment]
don't think I'm bitching, but have a look at our semi-official coding guidelines and mainly these ones:
- an { starts on a new line
- use descriptive names for variables and parameters.
- I would also suggest using hungarian notation for parameters and variables.
- use comments that doxygen can understand and, when you're documenting public methods, describe each parameter, return value and what happens when an error occurs

I'm looking at the posix implementations quickly again and adding comments in the patch. A windows dev (margro? :)) should have a look at the win32 implementations.

**Comment by lucianm** [comment]
On 21.04.2011 19:03, opdenkamp wrote:

> don't think I'm bitching, but have a look at our semi-official coding guidelines and mainly these ones:

It's ok, I only think I misunderstood what you in the end wanted me to
do, namely to actually re-write (and for this, understand every bit of)
the code, and not just move it around.

> - an { starts on a new line

That happens to be also my personal preference in daily coding at work,
but as mentioned, I didn't meant to change much just for the sake of
changing.

> - use descriptive names for variables and parameters.
> - I would also suggest using hungarian notation for parameters and variables.
> - use comments that doxygen can understand and, when you're documenting public methods, describe each parameter, return value and what happens when an error occurs

Alright, then I'll actually try to rewrite the code after understanding
all of the needed leftovers, then I can also document it.

> I'm looking at the posix implementations quickly again and adding comments in the patch. A windows dev (margro? :)) should have a look at the win32 implementations.

**Comment by margro** [comment]
I've had a quick look at the win32 implementation and I have no further comments other than the ones that opdenkamp already gave. Everything compiles fine and the compile warnings are gone now. Mediaportal pvr addon is still working fine. I can't test the VNSI and TVHeadend addon at the moment.

**Comment by lucianm** [comment]
Thanks, that is good top hear, I'll further tidy up. Then only TVHeadend
remains to be tested.

**Comment by lucianm** [comment]
Lars, I'd squash these last 3 commits into the initial 2 if you have no further comments and want to pull...

**Comment by opdenkamp** [comment]
thanks, looking good!
I'll give this one last review today and I'll pull it if there are no (serious) issues. if there are minor issues left, we'll clean that up after merging it.

**Comment by opdenkamp** [comment]
caught a little memory corruption issue in the tvheadend caused by your change because the win32 doesn't support VLA, but I'll fix that myself.

I'll also do some cosmetic edits and might change a couple of methods a bit later.

I'll squash the commits and merge them. thanks for your work

**Comment by opdenkamp** [comment]
squashed your commits in 79c8706edabd0fa409570b05a34702d43d7c6f8d and fixed the memory corruption issue in 6e09a5f94aa2897b0104f32db05f65bfa2a28f87

**Comment by opdenkamp** [comment]
oh and next time, don't send pull requests from your master branch, but from a branch that you can throw away later, because you'll get merge issues now and will need a push -f to fix it.

**Pull request closed without merging**
