### PR TITLE
two small fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
1)
channel up/down was(is) not working with vdr, vdr has no streamUrl. there is still a problem in vnsi which pipelka is digging in.

2)
i had epg updates every minute.

### CODE REVIEW

**Comment by opdenkamp** [comment]
1. I'll remove the empty streamurl check completely. the way you changed it isn't correct anyway. it would break the switch for clients that do have a streamurl set. the IsEmpty() would be false and SwitchChannel() wouldn't be called anymore.
2. the last scan time should only be persisted if the update succeeded for that table. if not, it will retry the update every minute.
   so the "m_lastScanTime = CDateTime::GetCurrentDateTime();" should be within the "if (bGrabSuccess)" block. it's getting the value from the db now every time, which isn't needed. on the other hand, that is what we'll have to do if we're going to support mysql or other multiuser db's properly. because that won't be supported any time soon (I'll have to change _a lot_ to make that possible), I'll just set the m_lastScanTime value.
   "m_lastScanTime = CDateTime(0);" isn't needed afaik because GetAsTime() will evaluate to 0 if the time isn't valid.

**Comment by opdenkamp** [comment]
if you had updates every minute, you probably have the epg database disabled in your options?

**Comment by opdenkamp** [comment]
could you check if 62ee0ca202e8edbcfae1bc60c7245e2debe60998 and c1ef4232e059a5e58de07cc2d02497ca41745c1f fix your issues please? if so, please close this pull request.

**Comment by FernetMenta** [comment]
i use vdr as backend which has its own epg cache. with epg database disabled startup is much faster.
your fixed do work. as already mentioned, there's still a problem in vnsi which reports an error when switching channels up/down.

**Pull request closed without merging**
