### PR TITLE
External addons

### PR DESCRIPTION
**Pull request by opdenkamp**
as a warning for those who aren't following the latest developments in my branches:
- this PR will remove all PVR add-ons from XBMC's tree
- the add-ons that were in XBMC's tree before have been moved to https://github.com/opdenkamp/xbmc-pvr-addons (except the myth add-on)
- the add-ons can be built by running "git submodule update --init pvr-addons" before running bootstrap, or built separately by checking out https://github.com/opdenkamp/xbmc-pvr-addons and following the instructions in the README file
- after this has been pushed, any change in the API will result in a PVR API version number bump

needs sync on win32. haven't checked OS-X since i don't have a mac.

comments welcome. i'll push this soon (tm) unless there are serious issues (things not building on windows right now is not one of them)

### CODE REVIEW

**Comment by elupus** [comment]
Nice

**Comment by margro** [comment]
I've sent you a pull request for the Windows build support.

**Comment by opdenkamp** [comment]
thanks, just merged it in. minor request: could you update the README file for windows too if you got time

**Comment by FernetMenta** [comment]
great! hit the green button :)

**Comment by opdenkamp** [comment]
i've changed the PVR_ERROR enum a bit, so i don't have to start with a version number bump right away.
and i've also updated the documentation in f872cfd. bit of c+p work in there, so i might have overlooked an error.

green button looks nice :)

**Pull request merged**
