### PR TITLE
vnsi addon

### PR DESCRIPTION
**Pull request by pipelka**
Sorry for this massive update. Changes include:
- connection lost & reconnect handling
- ui notification on connection lost & reconnect
- code simplification (removed iterated code duplication)
- memleak fixes
- allow the VDR server to request channel, timer & recordings updates

### CODE REVIEW

**Comment by opdenkamp** [comment]
I had a quick look at your patches. I can't test them, but they're looking sane to me. 112200f7af61649341910736bc29caa11dd87571 probably applies to tvheadend too.

one request: could you drop the "#ifdef **WINDOWS**" stuff and use libTcpSocket's methods instead.

**Comment by pipelka** [comment]
I can drop the "ifdef's" for network read / write operations (but this needs some testing).
I have to keep it for the SleepMs function for now (maybe a candidate for libPlatform).

**Comment by opdenkamp** [comment]
the methods in libTcpSocket should do exactly the same as yours. if not, and it doesn't work properly, it probably needs to be fixed in libTcpSocket too.

the sleep methods are a part of threading, which will probably get it's own separate lib. or it'll be added to the existing one. that part still needs some work.

**Comment by pipelka** [comment]
yes. i already pushed the change but it doesn't show up (i pulled it already to an other repository but it's not visible on the web interface).
maybe the server is currently busy and it takes some time, ...

**Pull request merged**
