### PR TITLE
pvr: improved german translation, added missing message key

### PR DESCRIPTION
**Pull request by xhaggi**
Improved the translation and added a missing message key

### CODE REVIEW

**Comment by opdenkamp** [comment]
"This pull request cannot be automatically merged."

**Comment by xhaggi** [comment]
is there a conflict?

**Comment by opdenkamp** [comment]
github thinks there is, so there's no nice green button for me now ;-)

**Comment by xhaggi** [comment]
i will merge your "master" into my "language branch" and apply my changes after that, hope that solves the conflict ;o)

**Pull request merged**
