### PR TITLE
confluence: epg start/end time before/after progress bar within channel osd ...

### PR DESCRIPTION
**Pull request by xhaggi**
I added the epg start/end time before/after the progress bar within the channel osd and the system date time to the header of the channel osd.

This improve the usability of the channel osd dialog.

### CODE REVIEW

**Comment by opdenkamp** [comment]
thanks. I'll test this first and will merge it in if ok. @JezzX, are you ok with these changes too?

**Comment by JezzX** [comment]
I have no issue with it as it looks fine but it has a graphical glitch if you have channel icons they overlap the end time for the item so you need to make them smaller or move the label
see http://i45.tinypic.com/dqqagz.png

**Comment by opdenkamp** [comment]
thanks for checking it

**Comment by xhaggi** [comment]
i will fix these glitches with the channel icons. i had not set up the channel icons in my development eviroment.

**Comment by xhaggi** [comment]
i made the channel icons a little bit smaller 40x40 so it fits the needs.

http://i50.tinypic.com/4h4i9e.png

**Comment by opdenkamp** [comment]
thanks, merged

**Pull request merged**
