### PR TITLE
French PVR translation and changes in code for ffmpeg

### PR DESCRIPTION
**Pull request by skylex**
- XBMC translation into French updated for PVR
- Changes in code to be able to build xbmc with ffmpeg's recents git revisions

Please review the commit acbc6ab before pulling it : I have put some comments that you need to convert in code because I don't know the correct way to do the checks that needs to be done.

Here is what changed in FFMPEG recently :
- libavcodec/opt.h doesn't need to be included anymore (the file has been removed)
- LIBAVCORE_VERSION_INT does not exist anymore
- av_set_string has been moved from dllAvCodec to dllAvUtil and renamed to av_set_string3 (the 4 lines in lib/DllAvCodec.h can be ignored if ffmpeg version > ?X?)
- CODEC_ID_XVID has been removed because xvid codec is included in CODEC_ID_MPEG4
- m_pCodecContext->hurry_up cannot be used anymore (it was already deprecated before)
- MAX_STREAMS needs to be defined in DVDDemuxFFmpeg.h
- CODEC_TYPE_xxx have been removed (they were duplicate of AVMEDIA_TYPE_xxx)

It was introduced in this FFmpeg commit FFmpeg/FFmpeg@6ed040408b26d8b5c896e60303a3bef6a39fa910 from September 26, 2010.

The changes I mention seems to work : I compiled xbmc-pvr after applying my patch https://gist.github.com/1010459 and everything went fine. However, this patch should not be applied on a system with an old version of ffmpeg.

I hope this helps ;)

### CODE REVIEW

**Comment by opdenkamp** [comment]
please squash all the translation related commits into one. the translations that are not specific to pvr should be sent to mainline xbmc (xbmc/master) or it could take months for it to be included.

I reviewed the ffmpeg related commits briefly. same as the other commits: send the changes that are not specific to pvr to mainline. also, these changes should not break existing installations with older ffmpegs (like the one included in our tree?).

**Comment by skylex** [comment]
ok no problem, I will do that.

team xbmc merged a commit some hours ago with the changes needed for latest ffmpeg, can you merge your fork ?

**Comment by opdenkamp** [comment]
the changes from mainline are merged approx. once a week, so it'll be merged in or after the week end.

**Comment by skylex** [comment]
Ok no problem.

I sent different pull requests as you suggested.

**Pull request closed without merging**
