### PR TITLE
epg: new gui setting that affects wether a popup should be displayed whe...

### PR DESCRIPTION
**Pull request by nemphys**
...n updating epg data from clients

### CODE REVIEW

**Comment by opdenkamp** [comment]
Please stick this in advancedsettings instead of the standard settings.

**Comment by nemphys** [comment]
Actually, that's what I started doing, but then I thought this kind of setting should be easily reached by a gui setting than having to edit xml files. Will do if you insist, but I find it better that way. Please advise

**Comment by opdenkamp** [comment]
no, I'd rather see this in advancedsettings. if you like to have a gui setting, make it a skin-specific setting.

edit:
please update the PR asap if you like to see it included in Eden-pvr, as Eden final will be tagged very soon, and Eden-pvr will follow shortly after.

**Comment by nemphys** [comment]
OK, will do it in advancedsettings, just tell me if you want it enabled by default or disabled

**Comment by nemphys** [comment]
Updated PR (it's enabled by default), please merge

**Comment by opdenkamp** [comment]
this also changes the current behaviour. right now, it's only displayed when doing the initial import, which is how I like to keep it by default. I'm fine with merging in a setting that controls this, but the current behaviour should remain the same when you don't set anything in as.xml.

**Comment by nemphys** [comment]
I know it does; actually, this is why I did this whole thing in the first place. Since there is a lot of disk activity (and hui stuttering sometimes) while the updates are taking place, I think it is better to notify the user why this is so.
Personally, I prefer it better.

**Comment by opdenkamp** [comment]
in that case, you're welcome to add a second setting in as.xml that controls this, but I still like to keep the current behaviour as it is. the reason is that I personally only care about the first import, when the epg is still being filled with new data and stuff in the gui is possibly still missing. all the rest normally just adds data at the back of the tables.

**Comment by nemphys** [comment]
ok, here you go, please merge :-)

**Comment by opdenkamp** [comment]
thanks, merged.

**Pull request merged**
