### PR TITLE
Pvr epg load on startup

### PR DESCRIPTION
**Pull request by FernetMenta**
Hi,

I fixed some issues. Not sure if this is the way you wanted it to be :)
1)
have the epg container create objects. it knows the type (epg or pvrepg)
2)
don't create new epgs for channels if they already exist
3)
the m_bStop flag prevented the initial load/update

### CODE REVIEW

**Comment by opdenkamp** [comment]
I'll have a look this evening. I might change a couple of things in your patch, but it's looking alright.

thanks for your work!

**Comment by opdenkamp** [comment]
I split up the patch in multiple little ones and changed a couple of things (e.g.the channel name does not have to be unique, so that can't be used to search for an existing table)

I'll push later today.

thanks for looking into the issues.

**Comment by FernetMenta** [comment]
cool, thanks for fixing it that fast. it actually was not intended to be a real patch, just to show what was wrong or not considered yet. it is always better when the owner of the code would do the patch to keep the style, and you do good job!
You might want to drop the call to Load in CPVREpgContainer start. that time settings have not been loaded and it is called on the next function anyhow.

**Comment by opdenkamp** [comment]
what call? :)

**Comment by FernetMenta** [comment]
in CPVREpgContainer::Start() do not call the Load method. or even better - just came to my mind right now - drop the entire method CPVREpgContainer::Start().

**Pull request closed without merging**
