### PR TITLE
tvheadend: fix bad error returned by GetEPG when last event has a (norma...

### PR DESCRIPTION
**Pull request by nemphys**
...l) next id of 0

### CODE REVIEW

**Comment by opdenkamp** [comment]
Could you check where that error is coming from first, because this change will also return no error when an error did occur

**Comment by nemphys** [comment]
I haven't yet checked the htsp code enough; when does it actually return a next id of 0? Does it also do it for errors, or just when it finishes sending events (my initial assumption)?

**Comment by nemphys** [comment]
Just took a look at the changes you introduced to the GetEpg method code with c73c7d973c7a8e647abd017234fb37a82a25 and I realized that before those changes, it would just return PVR_ERROR_NO_ERROR even after an error, that's why it didn't fail, ie. although it would try to read event with id 0 (after last event was sent with next id 0) and get an error from the client, it would just break the loop and return no error. I think the proposed implementation is better.
Will be waiting for your comments

**Comment by komadori82** [comment]
I am checking the HTSP protocol at the moment... but the problem is, it doesn't specify anywhere why there's a 0 as the next event id.

https://www.lonelycoder.com/redmine/projects/tvheadend/wiki/Htsp

**Comment by komadori82** [comment]
So, I dug a bit deeper into the HTSP sourcecode (which is nearly completely undocumented, btw) and this is what I found

/**
 *
 */
static htsmsg_t *
htsp_build_event(event_t *e)
{
  htsmsg_t *out;
  event_t *n;
  dvr_entry_t *de;

  out = htsmsg_create_map();

  htsmsg_add_u32(out, "eventId", e->e_id);
  htsmsg_add_u32(out, "channelId", e->e_channel->ch_id);
  htsmsg_add_u32(out, "start", e->e_start);
  htsmsg_add_u32(out, "stop", e->e_stop);
  if(e->e_title != NULL)
    htsmsg_add_str(out, "title", e->e_title);
  if(e->e_desc != NULL)
    htsmsg_add_str(out, "description", e->e_desc);
  if(e->e_ext_desc != NULL)
    htsmsg_add_str(out, "ext_desc", e->e_ext_desc);
  if(e->e_ext_item != NULL)
    htsmsg_add_str(out, "ext_item", e->e_ext_item);
  if(e->e_ext_text != NULL)
    htsmsg_add_str(out, "ext_text", e->e_ext_text);

  if(e->e_content_type)
    htsmsg_add_u32(out, "contentType", e->e_content_type);

  if((de = dvr_entry_find_by_event(e)) != NULL) {
    htsmsg_add_u32(out, "dvrId", de->de_id);
  }

  n = RB_NEXT(e, e_channel_link);
  if(n != NULL)
    htsmsg_add_u32(out, "nextEventId", n->e_id);

  return out;
}

It seems, it only adds the next id value, if it has one, otherwise it's "blank".

/**
- Get information about the given event
  */
  static htsmsg_t *
  htsp_method_getEvent(htsp_connection_t *htsp, htsmsg_t *in)
  {
  uint32_t eventid;
  event_t *e;
  htsmsg_t *out;
  
  if(htsmsg_get_u32(in, "eventId", &eventid))
    return htsp_error("Missing argument 'eventId'");
  
  if((e = epg_event_find_by_id(eventid)) == NULL)
    return htsp_error("Event does not exist");
  
  out = htsp_build_event(e);  
  return out;
  }

And here's what happens, if you inquire the event.id 0.

**Comment by nemphys** [comment]
Yeah, that's what I assumed in the first place (and sounds logical, anyway) with the difference that I thought tvheadend was sending a next event id of 0, whereas it seems it actually does not send the field at all (I suppose the receiving end is looking for such a field and assigns a 0 value to it since it's missing).
With that said, I think my solution is perfectly fine and solves the problem correctly.
@opdenkamp please give us your opinion

**Comment by opdenkamp** [comment]
ok merged, thanks

**Pull request merged**
