### PR TITLE
pvr: fix total time for recordings

### PR DESCRIPTION
**Pull request by FernetMenta**
total time was taken from epg instead of from recording.

### CODE REVIEW

**Comment by opdenkamp** [comment]
you should handle this all in CPVRManager or in CPVRFile, not half in class and the other half in another class.

**Comment by FernetMenta** [comment]
i was thinking about handling this in CPVRManager until i saw the m_isPlayRecording in CPVRFile.
what location do you prefer?

**Comment by FernetMenta** [comment]
i won't be able to change this until tomorrow evening and you know the code much better than i do. it's probably best closing this one you you'll fix it. ok?

**Comment by opdenkamp** [comment]
sure :) I'll stick it in cpvrmanager.

**Comment by opdenkamp** [comment]
meh. already moved that to cpvrguiinfo, so I'll correct it there

**Pull request closed without merging**
